import React from 'react'

export const images = [
    {
        id: 1,
        href: '/#',
        imageSrc: "/images/apartment/terrace33.jpg",
        name: "Terrace",
        username: "terrace",
    },
    {
        id: 2,
        href: '/#',
        imageSrc: "/images/apartment/terrace44.jpg",
        name: "Terrace",
        username: "terrace",
    },
    {
        id: 3,
        href: '/#',
        imageSrc: "/images/apartment/terrace.jpg",
        name: "Terrace",
        username: "terrace",
    },
    {
        id: 4,
        href: '/#',
        imageSrc: "/images/apartment/terracetable.jpg",
        name: "Terrace",
        username: "terrace",
    },
    {
        id: 5,
        href: '/#',
        imageSrc: "/images/apartment/terracesofa.jpg",
        name: "Terrace",
        username: "terrace",
    },
    {
        id: 6,
        href: '/#',
        imageSrc: "/images/apartment/livingroom.jpg",
        name: "Terrace",
        username: "terrace",
    },
    {
        id: 7,
        href: '/#',
        imageSrc: "/images/apartment/livingroomtable.jpg",
        name: "Terrace",
        username: "terrace",
    },
    {
        id: 8,
        href: '/#',
        imageSrc: "/images/apartment/kitchenhw.jpg",
        name: "Terrace",
        username: "terrace",
    },
    {
        id: 9,
        href: '/#',
        imageSrc: "/images/apartment/bathroom1.jpg",
        name: "Terrace",
        username: "terrace",
    },
    {
        id: 10,
        href: '/#',
        imageSrc: "/images/apartment/bedroom2xdb.jpg",
        name: "Terrace",
        username: "terrace",
    },
    {
        id: 11,
        href: '/#',
        imageSrc: "/images/apartment/bedroomdb.jpg",
        name: "Terrace",
        username: "terrace",
    },
    {
        id: 12,
        href: '/#',
        imageSrc: "/images/apartment/masterbroom22.jpg",
        name: "Terrace",
        username: "terrace",
    },
    {
        id: 13,
        href: '/#',
        imageSrc: "/images/apartment/mbathroom2.jpg",
        name: "Terrace",
        username: "terrace",
    },
    {
        id: 14,
        href: '/#',
        imageSrc: "/images/apartment/mbathroom3.jpg",
        name: "Terrace",
        username: "terrace",
    },
    {
        id: 15,
        href: '/#',
        imageSrc: "/images/apartment/mbedroom33.jpg",
        name: "Terrace",
        username: "terrace",
    },
    {
        id: 16,
        href: '/#',
        imageSrc: "/images/apartment/hallwayl2b.jpg",
        name: "Terrace",
        username: "terrace",
    },
    {
        id: 17,
        href: '/#',
        imageSrc: "/images/apartment/hw2kit.jpg",
        name: "Terrace",
        username: "terrace",
    },
    {
        id: 18,
        href: '/#',
        imageSrc: "/images/apartment/kitchenhw.jpg",
        name: "Terrace",
        username: "terrace",
    },
    {
        id: 19,
        href: '/#',
        imageSrc: "/images/garden/aparoutb.jpg",
        name: "Terrace",
        username: "terrace",
    },
    {
        id: 20,
        href: '/#',
        imageSrc: "/images/garden/aparoutc.jpg",
        name: "Terrace",
        username: "terrace",
    },
    {
        id: 21,
        href: '/#',
        imageSrc: "/images/garden/aparoutd.jpg",
        name: "Terrace",
        username: "terrace",
    },
    {
        id: 22,
        href: '/#',
        imageSrc: "/images/garden/apartaoutb.jpg",
        name: "Terrace",
        username: "terrace",
    },
    {
        id: 23,
        href: '/#',
        imageSrc: "/images/garden/apartouta.jpg",
        name: "Terrace",
        username: "terrace",
    },
    {
        id: 24,
        href: '/#',
        imageSrc: "/images/garden/apartoutc.jpg",
        name: "Terrace",
        username: "terrace",
    }
]




